os: linux
dist: focal
language: python

python:
  - "2.7"
  - "3.9"

services:
  - mongodb

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt -r requirements-dev.txt
before_script:
  - flake8 . --count --max-complexity=16 --show-source --statistics

script:
  - python -m app.server > /dev/null &
  - pytest --cov=./
  - kill $(lsof -t -i:7001)

after_success:
  - bash <(curl -s https://codecov.io/bash)
